version: "3.7"

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: backend/container_spec/nginx/Dockerfile
    depends_on:
      - api
    ports:
      - 8000:80
    expose:
      - 8000
    volumes:
      - ./backend/container_spec/nginx/cors_support:/etc/nginx/cors_support
      - ./backend/container_spec/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/container_spec/nginx/mime.types:/etc/nginx/mime.types

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"

  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: backend/container_spec/api/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      MYSQL_CONNECT_STRING: "user:password@tcp(mysql)/db?charset=utf8&parseTime=True&loc=Local"
