version: "3.7"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"

  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
    environment:
      MYSQL_CONNECT_STRING: "user:password@tcp(mysql)/db?charset=utf8&parseTime=True&loc=Local"
