name: ESLint Status Check

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  working-directory: ./frontend
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - uses: ouzi-dev/commit-status-updater@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Add NPX
      - name: Add NPX
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: add npx

      # Run `yarn lint` command
      - name: Run ESLint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint

      # Set status
      - if: success()
        uses: ouzi-dev/commit-status-updater@v0.1.1
        with:
          state: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: failure()
        uses: ouzi-dev/commit-status-updater@v0.1.1
        with:
          state: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
