name: React Build Status Check

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - uses: ouzi-dev/commit-status-updater@v0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install NodeJS & Yarn
        working-directory: .github/workflows
        run: |
          ls -al
          chmod +x node-install.sh
          chmod +x yarn-install.sh
          ./node-install.sh
          ./yarn-install.sh

      - name: Install Packages & Build Project
        working-directory: ./frontend
        run: yarn && yarn build

      # Set status
      - if: success()
        uses: ouzi-dev/commit-status-updater@v0.1.1
        with:
          state: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: failure()
        uses: ouzi-dev/commit-status-updater@v0.1.1
        with:
          state: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
