name: Golang Build Status Check

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    name: Golang Build Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set Pending
        uses: ouzi-dev/commit-status-updater@v0.1.1
        with:
          state: pending
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Get dependencies
        run: cs backend && go get -d -v
        
      - name: Build
        run: cd backend && go build -v .

      - name: Test
        run: cd backend && go test ./...

        # Set status
      - if: success()
        uses: ouzi-dev/commit-status-updater@v0.1.1
        with:
          state: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: failure()
        uses: ouzi-dev/commit-status-updater@v0.1.1
        with:
          state: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
